/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Pianale2_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.Scocca_blinn5_0.geometry} material={materials.blinn5} />
          <mesh geometry={nodes.pPipe7_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.Scarico1_scarico_0.geometry} material={materials.scarico} />
          <mesh geometry={nodes.pPipe6_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.Scarico2_scarico_0.geometry} material={materials.scarico} />
          <mesh geometry={nodes.pPipe9_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.Scarico3_scarico_0.geometry} material={materials.scarico} />
          <mesh geometry={nodes.pPipe11_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.Scarico4_scarico_0.geometry} material={materials.scarico} />
          <mesh geometry={nodes.polySurface38_WheelMat_0.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.polySurface39_WheelMat_0.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.pCylinder6_WheelMat_0.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.pPlane19_discoFrenoMat_0.geometry} material={materials.discoFrenoMat} />
          <mesh geometry={nodes.polySurface38_WheelMat_0_1.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.polySurface39_WheelMat_0_1.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.pCylinder6_WheelMat_0_1.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.pPlane19_discoFrenoMat_0_1.geometry} material={materials.discoFrenoMat} />
          <mesh geometry={nodes.polySurface38_WheelMat_0_2.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.polySurface39_WheelMat_0_2.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.pCylinder6_WheelMat_0_2.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.pPlane19_discoFrenoMat_0_2.geometry} material={materials.discoFrenoMat} />
          <mesh geometry={nodes.polySurface38_WheelMat_0_3.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.polySurface39_WheelMat_0_3.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.pCylinder6_WheelMat_0_3.geometry} material={materials.WheelMat} />
          <mesh geometry={nodes.pPlane19_discoFrenoMat_0_3.geometry} material={materials.discoFrenoMat} />
          <mesh geometry={nodes.ProfiloPosteriore_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.ParaurtiPosteriore_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.FaroPosterioreDx_GriglieFariFrecce_0.geometry} material={materials.GriglieFariFrecce} />
          <mesh geometry={nodes.FaroPosterioreSx_GriglieFariFrecce_0.geometry} material={materials.GriglieFariFrecce} />
          <mesh geometry={nodes.GrigliaPosteriore_GriglieFariFrecce_0.geometry} material={materials.GriglieFariFrecce} />
          <mesh geometry={nodes.FaroAnterioreSx_GriglieFariFrecce_0.geometry} material={materials.GriglieFariFrecce} />
          <mesh geometry={nodes.FaroAnterioreDx_defaultPolygonShader_0.geometry} material={materials.defaultPolygonShader} />
          <mesh geometry={nodes.RivestimentoCielo_RivestimentoTetto_0.geometry} material={materials.RivestimentoTetto} />
          <mesh geometry={nodes.GrigliaMotore_GriglieFariFrecce_0.geometry} material={materials.GriglieFariFrecce} />
          <mesh geometry={nodes.GrigliaAnteriore_GriglieFariFrecce_0.geometry} material={materials.GriglieFariFrecce} />
          <mesh geometry={nodes.PortatargaAnteriore_blinn5_0.geometry} material={materials.blinn5} />
          <mesh geometry={nodes.VetroPortaSx_vetro_0.geometry} material={materials.vetro} />
          <mesh geometry={nodes.VetroFissoPortaSx_vetro_0.geometry} material={materials.vetro} />
          <mesh geometry={nodes.Parabrezza_vetro_0.geometry} material={materials.vetro} />
          <mesh geometry={nodes.VetroFissoPortaDx_vetro_0.geometry} material={materials.vetro} />
          <mesh geometry={nodes.VetroPortaDx_vetro_0.geometry} material={materials.vetro} />
          <mesh geometry={nodes.VetroFissoPosterioreSx_vetro_0.geometry} material={materials.vetro} />
          <mesh geometry={nodes.VetroFissoPosterioreDx_vetro_0.geometry} material={materials.vetro} />
          <mesh geometry={nodes.Cruscotto_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.Esterno_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.Display_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.TunnelCentrale_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.Bocchetta1_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.pCylinder8_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.pCube11_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.pCube10_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.pTorus1_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.pCube12_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.pCube13_sediliMat_0.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube17_sediliMat_0.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube16_sediliMat_0.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube19_sediliMat_0.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube27_sediliMat_0.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube28_sediliMat_0.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.PannelloPortaDx_PannelliMat_0.geometry} material={materials.PannelliMat} />
          <mesh geometry={nodes.SottoTunnel_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.SupportoSpecchioInterno_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.RetrovisoreInterno_pianale_0.geometry} material={materials.pianale} />
          <mesh geometry={nodes.Bocchetta2_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.Bocchetta3_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.Bocchetta4_CruscottoPannelliMat_0.geometry} material={materials.CruscottoPannelliMat} />
          <mesh geometry={nodes.pCube13_sediliMat_0_1.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube17_sediliMat_0_1.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube16_sediliMat_0_1.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube19_sediliMat_0_1.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube27_sediliMat_0_1.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.pCube28_sediliMat_0_1.geometry} material={materials.sediliMat} />
          <mesh geometry={nodes.PannelloSx_PannelliMat_0.geometry} material={materials.PannelliMat} />
          <mesh geometry={nodes.Sinistro_blinn5_0.geometry} material={materials.blinn5} />
          <mesh geometry={nodes.SpecchioSx_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.Destro_blinn5_0.geometry} material={materials.blinn5} />
          <mesh geometry={nodes.SpecchioDx_lambert1_0.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
